### ISSUE TITLE
Raise a signal when using Traversal / Prism to modify data but it couldn't locate any element in array by predicate

### ISSUE THREAD

**Issue by lanyusan** [gcanti/monocle-ts#118]
## 🚀 Feature request

When use Traversal / Prism to modify an item in an array by predicate, if no element is found, a signal should be raised to indicate that.

### Current Behavior

Existing object is returned silently.

### Suggested Solution

Throw an exception indicating element  not found

Example test code can be found at issue #117

**Comment by kylegoetz** [comment]
I don't think you can do this and have your optics still obey the optics laws. Modify means "change what you're focused on and then give me the updated state" and if you aren't focused on something, then you can't change it, so you skip the first step.

One of the (math-based) laws of traversals is that a modification of a traversal must result in a traversable with the same number of items. If your modify returned an error in some cases, it would violate this law.

Put another way, how do you compose traversals if one of them can return an error but the other must take a traversable?

And because prisms are a special type of traversal, it must obey the same law.

You're misunderstanding the purpose of traversal.
