### ISSUE TITLE
Cannot create a generic Lense 

### ISSUE THREAD

**Issue by sledorze** [gcanti/monocle-ts#75]
The problem started with version 1.5.2, (worked in version 1.5.1).

```typescript
export interface Indexed {
  index: number
}
const indexedLenseOK = m.Lens.fromPath<Indexed, 'index'>(['index'])
const indexedLenseKO = <T extends Indexed>() => m.Lens.fromPath<T, 'index'>(['index']) // '"index"' does not satisfy the constraint 'ObjectProp<T>'
```

This is related to 
https://github.com/gcanti/monocle-ts/commit/27b587bd052edbef0a68a7a60d730fa91d60430a

**Comment by sledorze** [comment]
@gcanti thanks!

**Comment by joshburgess** [comment]
Any thoughts on how we could go about keeping those safe guards without causing this unexpected problem? I might try to work on bringing that PR back if I can figure out how to do it without causing this breakage.

**Comment by gcanti** [comment]
@joshburgess maybe when negated type are a thing, but honestly after what happended I will be more wary to accept type level tricks.
Also because TypeScript is a moving target, this snippet if perfectly fine with `typescript@3.3.1` but is failing with `typescript@next` (tried again a couple of minutes ago)

```ts
interface Thing {
  a: {
    b: number
  }
}

const getLensFromPath = <T extends Thing>(): Lens<T, number> => Lens.fromPath<T>()(['a', 'b'])
```
